/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobinarios;

import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.ListModel;

/**
 *
 * @author Usuario
 */
public class Constantes implements Serializable{
    
    String CABECERASHISTORIALACADEMICO,TIPOSDEDATOSHISTORIALACADEMICO,
            CABECERASNRCESTUDIANTESACTIVOS, TIPOSDEDATOSNRCESTUDIANTESACTIVOS, 
            CABECERASCURRICULOS,TIPODEDATOSCURRICULOS, 
            CABECERASESTUDIANTESACTIVOSGENERAL, TIPOSDEDATOSESTUDIANTESACTIVOSGENERAL,
            CABECERASPROGRAMACIONACADEMICAARGOS, TIPOSDEDATOSPROGRAMACIONACADEMICAARGOS;
    
    ArrayList<String> DLHISTORIALACADEMICO, DLNRCESTUDIANTESACTIVOS, 
            DLCURRICULOS,DLESTUDIANTESACTIVOSGENERAL,
            DLPROGRAMACIONACADEMICAARGOS;
    
    public Constantes(String CABECERASHISTORIALACADEMICO, 
            String TIPOSDEDATOSHISTORIALACADEMICO, 
            String CABECERASNRCESTUDIANTESACTIVOS, 
            String TIPOSDEDATOSNRCESTUDIANTESACTIVOS, 
            String CABECERASCURRICULOS, 
            String TIPODEDATOSCURRICULOS, 
            String CABECERASESTUDIANTESACTIVOSGENERAL, 
            String TIPOSDEDATOSESTUDIANTESACTIVOSGENERAL, 
            String CABECERASPROGRAMACIONACADEMICAARGOS, 
            String TIPOSDEDATOSPROGRAMACIONACADEMICAARGOS, 
            ArrayList<String> DLHISTORIALACADEMICO, 
            ArrayList<String> DLNRCESTUDIANTESACTIVOS, 
            ArrayList<String> DLCURRICULOS, 
            ArrayList<String> DLESTUDIANTESACTIVOSGENERAL, 
            ArrayList<String> DLPROGRAMACIONACADEMICAARGOS) {
        this.CABECERASHISTORIALACADEMICO = CABECERASHISTORIALACADEMICO;
        this.TIPOSDEDATOSHISTORIALACADEMICO = TIPOSDEDATOSHISTORIALACADEMICO;
        this.CABECERASNRCESTUDIANTESACTIVOS = CABECERASNRCESTUDIANTESACTIVOS;
        this.TIPOSDEDATOSNRCESTUDIANTESACTIVOS = TIPOSDEDATOSNRCESTUDIANTESACTIVOS;
        this.CABECERASCURRICULOS = CABECERASCURRICULOS;
        this.TIPODEDATOSCURRICULOS = TIPODEDATOSCURRICULOS;
        this.CABECERASESTUDIANTESACTIVOSGENERAL = CABECERASESTUDIANTESACTIVOSGENERAL;
        this.TIPOSDEDATOSESTUDIANTESACTIVOSGENERAL = TIPOSDEDATOSESTUDIANTESACTIVOSGENERAL;
        this.CABECERASPROGRAMACIONACADEMICAARGOS = CABECERASPROGRAMACIONACADEMICAARGOS;
        this.TIPOSDEDATOSPROGRAMACIONACADEMICAARGOS = TIPOSDEDATOSPROGRAMACIONACADEMICAARGOS;
        this.DLHISTORIALACADEMICO = DLHISTORIALACADEMICO;
        this.DLNRCESTUDIANTESACTIVOS = DLNRCESTUDIANTESACTIVOS;
        this.DLCURRICULOS = DLCURRICULOS;
        this.DLESTUDIANTESACTIVOSGENERAL = DLESTUDIANTESACTIVOSGENERAL;
        this.DLPROGRAMACIONACADEMICAARGOS = DLPROGRAMACIONACADEMICAARGOS;

    }
    
    
    
            
    
}
