/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobinarios;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaEnsayosTabla extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEnsayosTabla
     */
    public VentanaEnsayosTabla() {
        initComponents();
        iniciar();
    }

    public void iniciar() {

        try {
            Connection conn = ConsultasSQL.conexionBD(ConsultasSQL.NOMBREBDOFERTAEDUCATIVA);
            String sede = "PER";
            String programa = "PSID";
            String curriculo = "PSID"/*"UVASST20182"*/;
            int semestre = 10;

            String sqlHistorialQueTengaHastaSemestreN
                    = EstudiantesPorPrograma.crearTablaTemporalHistorialAcademicoAprobadosHastaSemestreN(
                            conn, programa, curriculo, sede, semestre);

            ResultSet rs = conn.createStatement().executeQuery("select * from "
                    + sqlHistorialQueTengaHastaSemestreN
                    + " group by ID_ESTUDIANTE ");

            String tablaAsignaturasHastaSemestre = EstudiantesPorPrograma.
                    crearTablaTemporalAsignaturasCarreraCurriculoHastaSemestre(conn, programa, curriculo, semestre);
            
            while (rs.next()) {
               
                String nombreTablaEstudianteHastaSemestre = EstudiantesPorPrograma.
                        crearTablaTemporalHistorialEstudianteHastaSemestre(conn,
                                Integer.parseInt((String) rs.getObject(1)),
                                semestre,
                                sqlHistorialQueTengaHastaSemestreN,
                                programa,
                                curriculo,
                                sede);

                boolean enBloque = EstudiantesPorPrograma.estudianteEnBloqueSemestreDado(Integer.parseInt((String) rs.getObject(1)),
                        semestre,
                        conn,
                        tablaAsignaturasHastaSemestre,
                        nombreTablaEstudianteHastaSemestre);

                System.out.println("Estudiante " + rs.getObject(1) + " va en bloque " + enBloque);
            }

            String sql = "select * from " + "estudiante"
                    + 680540 + "semestre" + semestre;
            ResultSet rsestudiante = conn.createStatement().executeQuery(sql);
            DefaultTableModel dtm = new DefaultTableModel();
            ConversorResultSetADefaultTableModel.rellena(rsestudiante, dtm);
            jTableEnsayos.setModel(dtm);
            
            ResultSet rstablaasignaturas = conn.createStatement().executeQuery("select * from " + tablaAsignaturasHastaSemestre);
            dtm = new DefaultTableModel();
            ConversorResultSetADefaultTableModel.rellena(rstablaasignaturas, dtm);
            jTableEnsayos2.setModel(dtm);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnsayos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEnsayos2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTableEnsayos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEnsayos);

        getContentPane().add(jScrollPane1);

        jTableEnsayos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableEnsayos2);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEnsayosTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEnsayos;
    private javax.swing.JTable jTableEnsayos2;
    // End of variables declaration//GEN-END:variables
}
