/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobinarios;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaEnsayosTabla1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEnsayosTabla
     */
    public VentanaEnsayosTabla1() {
        initComponents();
        iniciar();
    }

    public void iniciar() {

        try {
            Connection conn = ConsultasSQL.conexionBD(ConsultasSQL.NOMBREBDOFERTAEDUCATIVA);
            String sede = "PER";
            String programa = "PSID";
            String curriculo = "PSID"/*"UVASST20182"*/;

            String nombreTablaSemestre1 = EstudiantesPorPrograma.crearTablaTemporalAsignaturasCarreraCurriculoDado(conn, programa, curriculo);

            ResultSet rs = conn.createStatement().executeQuery("select * from "
                    + nombreTablaSemestre1);
//                    +" where semestre=1");

            ConsultasSQL.crearTablaTemporalEstudiantesActivosArgosSinRepetir(conn);
            EstudiantesNoHanVistoNRC enhv = new EstudiantesNoHanVistoNRC(conn, sede, programa, curriculo);
            
            enhv.crearTablaTemporalFinalNoLaHanVistoLaPuedenVer();

            ArrayList<String> materias = new ArrayList<String>();
            ArrayList<String> alfaNumericos = new ArrayList<String>();

            while (rs.next()) {
                String anEvaluar = rs.getString("alfanumerico");
                String asignatura = rs.getString("asignatura");
                materias.add(asignatura);
                alfaNumericos.add(anEvaluar);
            }

            String sqlUnion = "";
            String sql3 = "";
            int tamano = materias.size();
//            tamano = 4;
            for (int i = 0; i < tamano; i++) {
                sql3 = " select "
                            + ConsultasSQL.NOMBRETABLATEMPORAL_ESTUDIANTESACTIVOS + ".*, "
                            + "'"+ materias.get(i)+"' as asignatura, '" +alfaNumericos.get(i)+ "' as alfaNumerico, "
                            + enhv.NOMBRETABLANOHANVISTOYPUEDENVER + alfaNumericos.get(i) + ".creditosaprobados "
                            + " from "
                            + enhv.NOMBRETABLANOHANVISTOYPUEDENVER + alfaNumericos.get(i)
                            + " LEFT JOIN "
                            + ConsultasSQL.NOMBRETABLATEMPORAL_ESTUDIANTESACTIVOS
                            + " ON "
                            + enhv.NOMBRETABLANOHANVISTOYPUEDENVER + alfaNumericos.get(i) + "." + ConsultasSQL.COLUMNACODIGOESTUDIANTEHISTORIALACADEMICO
                            + "="
                            + ConsultasSQL.NOMBRETABLATEMPORAL_ESTUDIANTESACTIVOS + "." + ConsultasSQL.COLUMNACODIGOESTUDIANTESACTIVOSARGOS
                            ;
                if (i != tamano - 1) {
                    sqlUnion =   sqlUnion+" "+sql3+  " union ";
                    //sqlUnion = sqlUnion + " select '"+ materias.get(i)+"' as asignatura, '" +alfaNumericos.get(i)+ "' as alfaNumerico, " + nombresTablas.get(i)+".* from " + nombresTablas.get(i) + " union all ";
                } else {
                    sqlUnion = sqlUnion + sql3 + " order by asignatura ";
                    //sqlUnion = sqlUnion + " select '"+ materias.get(i)+"' as asignatura, '" +alfaNumericos.get(i)+ "' as alfaNumerico, " + nombresTablas.get(i)+".* from " + nombresTablas.get(i);
                }
            }
            System.out.println(sqlUnion);

            ResultSet rs2 = conn.createStatement().executeQuery(sqlUnion);

//            ArrayList<ArrayList<Object>> al =ConversorResultSetArrayList.resultSetToArrayList(rs);
//            ResultSet rs = conn.createStatement().executeQuery("select *  from "
//                    + EstudiantesPorPrograma.crearTablaTemporalAprobadosPendientes(conn, sede, programa, curriculo));
//            DefaultTableModel dtm = new DefaultTableModel();
//            ConversorResultSetADefaultTableModel.rellena(rs, dtm);
//            jTableEnsayos.setModel(dtm);
            new JFrameJTable("todas las tablas", rs2);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnsayos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTableEnsayos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEnsayos);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEnsayosTabla1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEnsayos;
    // End of variables declaration//GEN-END:variables
}
