/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobinarios;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaEnsayosTablaArrayList extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEnsayosTabla
     */
    public VentanaEnsayosTablaArrayList() {
        initComponents();
        iniciar();
    }

    public void iniciar() {

        try {
            Connection conn = ConsultasSQL.conexionBD(ConsultasSQL.NOMBREBDOFERTAEDUCATIVA);
            String sede = "PER";
            String programa = "LPID";
            String curriculo = "LPID"/*"UVASST20182"*/;

            String nombreTablaSemestre1 = EstudiantesPorPrograma.crearTablaTemporalAsignaturasCarreraCurriculoDado(conn, programa, curriculo);
            int semestre = 1;
            String selectPrimerSemestre = "select alfanumerico "
                    + " from "
                    + nombreTablaSemestre1
                    + " where "
                    + " semestre=" + semestre;

//            ArrayList<ArrayList<Object>> al = SelectsEnArrayList.aNAsignaturasSemestre(conn, programa, curriculo, 1);
//            ArrayList<ArrayList<Object>> al = SelectsEnArrayList.idEstudiantesAprobadosSemestre(conn, sede, programa, 1);
            String nombreTablaTemporalHistorialAcademico = EstudiantesPorPrograma.crearTablaTemporalHistorialAcademicoSedeCarreraCurriculoDado(conn, sede, programa);
            String nombreTablaHistorialAnEquivalentes = EstudiantesPorPrograma.crearTablaTemporalHistorialAcademicoAlfaNumericosEquivalentes(conn, nombreTablaTemporalHistorialAcademico);
            String nTHistorialAprobados = EstudiantesPorPrograma.crearTablaTemporalObtenerHistorialTemporalSegunNota(conn, nombreTablaHistorialAnEquivalentes, ">=", 3);

            String sqlHistorialQueTengaAlasSemestre1
                    = "select * from " + nTHistorialAprobados
                    + " where "
                    + " alfanumerico "
                    + "in("
                    + selectPrimerSemestre
                    + ")"
                    + " or alfaNumericoEquivalente in "
                    + "(" + selectPrimerSemestre + " ) "
                    + " group by ID_ESTUDIANTE, alfanumerico";
            
            

            DefaultTableModel dtm = new DefaultTableModel();
            ConversorArrayListJTable.rellena(ConversorResultSetArrayList.selectToArrayList(conn, sqlHistorialQueTengaAlasSemestre1), dtm);
            jTableEnsayos.setModel(dtm);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnsayos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTableEnsayos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEnsayos);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTablaArrayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTablaArrayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTablaArrayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEnsayosTablaArrayList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEnsayosTablaArrayList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEnsayos;
    // End of variables declaration//GEN-END:variables
}
